name: Check code quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check for syntax errors
        run: pylint --exit-zero src

      - name: Check for style violations
        run: pylint --exit-zero --disable=all --enable=style src

      - name: Check for typos
        run: pylint --exit-zero --disable=all --enable=spelling --spelling-dict=en_US src
