name: Run main.py

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI_check:
    name: CI check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test_notebook.py
        run: python test/test_notebook.py

      - name: Verify exit code
        run: |
          if [ $? -ne 0 ]; then
            echo "Error: test_notebook.py failed to run."
            exit 1
          else
            echo "Success: test_notebook.py ran without errors."
          fi
