name: PEP8 check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pep8:
    name: PEP8 check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run linter
        run: pylint src